version: "3.9"
services:
  backend:
    image: custom.registry:443/path/dipendentepubico/concorsiparentibackend
    depends_on:
      - database
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/cpd
      DATABASE_USERNAME: theusername
      DATABASE_PASSWORD: thepassword
      FRONTEND_URL: http://server-prod:24401
  database:
    image: postgres:10.20
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: cpd
    # porta per test su db
#    ports:
#      - "5432:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
  # adiminer per test su db
  dbmanager:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"